[window]
dynamic_padding = true
opacity = 0.8

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size = 13

[env]
term = "xterm-256color"

[cursor]
style = { shape = "Block", blinking = "Always" }
