[window]
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 15

[env]
term = "xterm-256color"

[cursor]
style = { shape = "Block", blinking = "Always" }
