[window]
dynamic_padding = true

[font]
normal = { family = "JetbrainsMono NF", style = "Regular" }
size = 14.0

[env]
term = "xterm-256color"

[cursor]
style = { shape = "Block", blinking = "Always" }

# [colors.primary]
# background = "#000000"
