[window]
dynamic_padding = false

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 14

[env]
term = "xterm-256color"

[cursor]
style = { shape = "Block", blinking = "Always" }

[colors.primary]
background = "#181818"
