window:
  dynamic_padding: true
  opacity: 0.8

font:
  normal:
    family: "JetBrainsMono Nerd Font Mono"
    style: "Regular"
  size: 11

env:
  term: "xterm-256color"

colors:
  # Tomorrow (https://github.com/aarowill/base16-alacritty/blob/master/colors/base16-tomorrow.yml)
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xdddddd'

cursor:
  style:
    shape: "Block"
    blinking: "Always"

